name = "chat"
version = "0.1.0"
description = "chat actor for LLM chat application using content-fs for storage"
component_path = "/nix/store/5by33rv9w1kidrz4nx103l23m63y99av-chat-actor-0.1.0/lib/chat.wasm"
init_state = "/Users/colinrozzi/work/actors/chat/init.json"

[interface]
implements = "ntwk:theater/single-actor"
requires = []

[[handlers]]
type = "runtime"
config = {}

# We no longer need the filesystem handler since we're using runtime-content-fs!
[[handlers]]
type = "filesystem"
config = { path = "/Users/colinrozzi/work/actors/chat/assets"}

[[handlers]]
type = "store"
config = {}

[[handlers]]
type = "http-framework"
config = {}

[[handlers]]
type = "http-client"
config = {}

[[handlers]]
type = "supervisor"
config = {}
