name = "HTML Demo Actor"
version = "0.1.0"
description = "Demonstrates the HTML rendering capabilities of child actors"
component_path = "/Users/colinrozzi/work/actors/hello-child/target/wasm32-unknown-unknown/release/hello_child.wasm"

[interface]
implements = "ntwk:theater/actor"
requires = []

[[handlers]]
type = "runtime"
config = {}
