name = "sentiment-analyzer"
version = "0.1.0"
description = "Analyzes the sentiment of chat messages"
component_path = "/Users/colinrozzi/work/actors/sentiment-analyzer/target/wasm32-wasi/release/sentiment_analyzer.wasm"

[interface]
implements = "ntwk:theater/actor"
requires = []

[[handlers]]
type = "message-server"
config = {}